name: ex1

on: push

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
    - name: Step one
      uses: actions/checkout@v3
    - name: Step two
      run: echo "The date is: $(date)"
  job2:
    name: Second job
    runs-on: windows-latest
    steps:
    - name: Step one
      uses: actions/checkout@v3
    - name: step two
      run: Write-Host "Windows Date is:" Get-Date 
  job3:
    name: Third job
    runs-on: macos-latest
    steps:
    - name: Step one
      uses: actions/checkout@v3
    - name: step two
      run: date 
  job4:
    name: Fourth job
    runs-on: ubuntu-latest
    needs: [job1,job2,job3,job4]
    steps:
    - name: Step one
      uses: actions/checkout@v3
    - name: step two
      run: echo "The date is: $(date)"